global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: xenserver
  scrape_interval: 60s
  scrape_timeout: 50s
  static_configs:
   - targets:
     - xen01:9100
     - xen02:9100
     - xen03:9100
     - xen04:9100
     - xen05:9100
     - xen06:9100
